### PR TITLE
impr(summarize-api): improve summarization API and documentation

### PR DESCRIPTION
**Pull request by williamlaitpe**
- Refactored and improved content summarization API
  - Added content summarization controller
  - Added Python script executor
  - Added test cases
 
- Improved README with more details
  - Added installation and configuration instructions
  - Added credits and acknowledgments
  
- Updated Python virtual environment setup
  - Updated virtual environment configuration

### CODE REVIEW

**Review by whyimhere — COMMENTED** [review]
emmm, can you explain why you choose to remove your api from the api package, and move it to where? Kera and I both put a lot of APIs into this package

**Comment by williamlaitpe** [comment]
I’m unsure if packaging needs to strictly adhere to clean architecture. Since I’ve handled data saving and API components, I think it’s reasonable to create a framework package for all external applications, including API usage, data saving, and future database interactions.

    To follow SOLID principles, I separated and moved part of the original API class (Python script, executor, and output handler) to the framework package. The interface adapter now contains the remaining part of the original API class, including controllers to call scripts and helper classes to manage API usage limits.

Hope this helps clarify things.

**Comment by williamlaitpe** [comment]
I’m unsure if packaging needs to strictly adhere to clean architecture. Since I’ve handled data saving and API components, I think it’s reasonable to create a framework package for all external applications, including API usage, data saving, and future database interactions.

**Comment by williamlaitpe** [comment]
To follow SOLID principles, I separated and moved part of the original API class (Python script, executor, and output handler) to the framework package. The interface adapter now contains the remaining part of the original API class, including controllers to call scripts and helper classes to manage API usage limits.

**Comment by whyimhere** [comment]
> To follow SOLID principles, I separated and moved part of the original API class (Python script, executor, and output handler) to the framework package. The interface adapter now contains the remaining part of the original API class, including controllers to call scripts and helper classes to manage API usage limits.

OK, we can figure out which way is better in Sunday, now first implement those use cases

**Pull request merged**
